//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosEMontesdeoca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cuentas
    {
        [Key]
        public int IdCuenta { get; set; }
        public int IdCliente { get; set; }
        public int IdEntidad { get; set; }
        [StringLength(20, MinimumLength = 10, ErrorMessage = "Minimo 10 numeros.")]
        public string NumCuenta { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
    }
}
