//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosEMontesdeoca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cuentas
    {
        [Key]
        public int IdCuenta { get; set; }
        public int IdCliente { get; set; }
        public int IdEntidad { get; set; }

        [Required]
        [StringLength(10, ErrorMessage = "Maximo 10 numeros.")]
        public string NumCuenta { get; set; }

        [Column(TypeName = "date")]
        [Required(ErrorMessage = "Fecha de registro requerida")]
        [DataType(DataType.Date, ErrorMessage = "Fecha registro incorrecta")]
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        //[MinLength(1, ErrorMessage = "Minimo tiene que tener 1 euro")]
        [Required]
        [Range(0, double.MaxValue, ErrorMessage = "El valor debe de ser mayor que 0")]
        public Nullable<decimal> Saldo { get; set; }

        public virtual Clientes Clientes { get; set; }
        public virtual Entidades Entidades { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
    }
}
