//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancosEMontesdeoca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Operaciones
    {
        [Key]
        public int IdOperacion { get; set; }
        public int IdCliente { get; set; }
        public int Tipo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
